'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.17929
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
'à l'aide d'un outil, tel que ResGen ou Visual Studio.
'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
'avec l'option /str ou régénérez votre projet VS.
'''<summary>
'''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class Form1
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ConnexIDE.Form1", GetType(Form1).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
    '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property buildAndRunToolStripMenuItem_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("buildAndRunToolStripMenuItem.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property buildToolStripMenuItem_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("buildToolStripMenuItem.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property copyToolStripButton_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("copyToolStripButton.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property cutToolStripButton_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("cutToolStripButton.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property helpToolStripButton_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("helpToolStripButton.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=17,Y=17}.
    '''</summary>
    Friend Shared ReadOnly Property menuStrip1_TrayLocation() As System.Drawing.Point
        Get
            Dim obj As Object = ResourceManager.GetObject("menuStrip1.TrayLocation", resourceCulture)
            Return CType(obj,System.Drawing.Point)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property newToolStripButton_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("newToolStripButton.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=17,Y=56}.
    '''</summary>
    Friend Shared ReadOnly Property openFileDialog1_TrayLocation() As System.Drawing.Point
        Get
            Dim obj As Object = ResourceManager.GetObject("openFileDialog1.TrayLocation", resourceCulture)
            Return CType(obj,System.Drawing.Point)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property openToolStripButton_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("openToolStripButton.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property pasteToolStripButton_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("pasteToolStripButton.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property runInConsoleToolStripMenuItem_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("runInConsoleToolStripMenuItem.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=126,Y=17}.
    '''</summary>
    Friend Shared ReadOnly Property saveFileDialog1_TrayLocation() As System.Drawing.Point
        Get
            Dim obj As Object = ResourceManager.GetObject("saveFileDialog1.TrayLocation", resourceCulture)
            Return CType(obj,System.Drawing.Point)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=254,Y=17}.
    '''</summary>
    Friend Shared ReadOnly Property saveFileDialog2_TrayLocation() As System.Drawing.Point
        Get
            Dim obj As Object = ResourceManager.GetObject("saveFileDialog2.TrayLocation", resourceCulture)
            Return CType(obj,System.Drawing.Point)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property saveToolStripButton_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("saveToolStripButton.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=481,Y=17}.
    '''</summary>
    Friend Shared ReadOnly Property statusStrip1_TrayLocation() As System.Drawing.Point
        Get
            Dim obj As Object = ResourceManager.GetObject("statusStrip1.TrayLocation", resourceCulture)
            Return CType(obj,System.Drawing.Point)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=597,Y=17}.
    '''</summary>
    Friend Shared ReadOnly Property timer1_TrayLocation() As System.Drawing.Point
        Get
            Dim obj As Object = ResourceManager.GetObject("timer1.TrayLocation", resourceCulture)
            Return CType(obj,System.Drawing.Point)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property toolStrip1_BackgroundImage() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("toolStrip1.BackgroundImage", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=382,Y=17}.
    '''</summary>
    Friend Shared ReadOnly Property toolStrip1_TrayLocation() As System.Drawing.Point
        Get
            Dim obj As Object = ResourceManager.GetObject("toolStrip1.TrayLocation", resourceCulture)
            Return CType(obj,System.Drawing.Point)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property toolStripButton1_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("toolStripButton1.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property toolStripButton2_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("toolStripButton2.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property toolStripButton3_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("toolStripButton3.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property vIPERVMDebugWindowToolStripMenuItem_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("vIPERVMDebugWindowToolStripMenuItem.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
End Class
